kind: pipeline
name: default

steps:
 - name: fmt
   image: rust:1.43.0
   commands:
     - rustup component add rustfmt
     - cargo fmt --all -- --check
 - name: test
   image: shimun/fido2luks@sha256:6d0b4017bffbec5fac8f25d383d68671fcc9930efb02e97ce5ea81acf0060ece
   environment:
    DEBIAN_FRONTEND: noninteractive
   commands:
    - cargo test --locked
 - name: publish
   image: shimun/fido2luks@sha256:6d0b4017bffbec5fac8f25d383d68671fcc9930efb02e97ce5ea81acf0060ece
   environment:
    DEBIAN_FRONTEND: noninteractive
    CARGO_REGISTRY_TOKEN:
     from_secret: cargo_tkn
   commands:
    - grep -E 'version ?= ?"${DRONE_TAG}"' -i Cargo.toml || (printf "incorrect crate/tag version" && exit 1)
    - cargo package --all-features --allow-dirty
    - cargo publish --all-features --allow-dirty
   when:
    event: tag
